"""
============================================================
FEATURE CONFIGURATION
============================================================

Loads the production feature configuration generated by the
IC pipeline.

Input
-----
master_table_ic.csv

Output
------
FeatureWeightConfig

Used by
-------
Composite Scoring Engine
Portfolio Construction
Backtester
Future Optimization Modules
============================================================
"""

from dataclasses import dataclass
from pathlib import Path
from typing import Dict, List

import numpy as np
import pandas as pd


# ============================================================
# CONFIG OBJECT
# ============================================================

@dataclass(frozen=True)
class FeatureWeightConfig:
    """
    Immutable production configuration for the scoring engine.
    """

    features: List[str]
    weights: Dict[str, float]
    feature_rank: Dict[str, int]
    metadata: Dict


# ============================================================
# REQUIRED COLUMNS
# ============================================================

REQUIRED_COLUMNS = [
    "Feature",
    "Adaptive_Weight",
    "Feature_Rank",
    "Use_Feature",
]


# ============================================================
# VALIDATION
# ============================================================

def _validate_master_table(df: pd.DataFrame) -> None:
    """
    Validate IC master table.
    """

    missing = [
        col
        for col in REQUIRED_COLUMNS
        if col not in df.columns
    ]

    if missing:
        raise ValueError(
            f"Missing required columns: {missing}"
        )

    if not df["Feature"].is_unique:
        duplicates = (
            df["Feature"]
            .value_counts()
            .loc[lambda x: x > 1]
        )

        raise ValueError(
            f"Duplicate features detected:\n{duplicates}"
        )


# ============================================================
# LOAD CONFIGURATION
# ============================================================

def load_feature_config(
    csv_path: str | Path
) -> FeatureWeightConfig:
    """
    Load production feature configuration.

    Parameters
    ----------
    csv_path : str or Path

    Returns
    -------
    FeatureWeightConfig
    """

    csv_path = Path(csv_path)

    if not csv_path.exists():
        raise FileNotFoundError(csv_path)

    df = pd.read_csv(csv_path)

    _validate_master_table(df)

    # --------------------------------------------------------
    # Keep selected features only
    # --------------------------------------------------------

    df = (
        df[df["Use_Feature"] == True]
        .copy()
    )

    if df.empty:
        raise ValueError(
            "No production features selected."
        )

    # --------------------------------------------------------
    # Feature Rank must exist
    # --------------------------------------------------------

    if df["Feature_Rank"].isna().any():

        raise ValueError(
            "Selected feature(s) missing Feature_Rank."
        )

    # --------------------------------------------------------
    # Weight sanity
    # --------------------------------------------------------

    df["Adaptive_Weight"] = (
        df["Adaptive_Weight"]
        .fillna(0)
        .clip(lower=0)
    )

    weight_sum = float(
        df["Adaptive_Weight"].sum()
    )

    normalized = False

    if not np.isclose(weight_sum, 1.0):

        if weight_sum <= 0:

            raise ValueError(
                "Adaptive weights sum to zero."
            )

        df["Adaptive_Weight"] /= weight_sum
        normalized = True
        weight_sum = float(
            df["Adaptive_Weight"].sum()
        )

    # --------------------------------------------------------
    # Sort by rank
    # --------------------------------------------------------

    df = df.sort_values(
        "Feature_Rank"
    ).reset_index(drop=True)

    # --------------------------------------------------------
    # Build dictionaries
    # --------------------------------------------------------

    features = (
        df["Feature"]
        .tolist()
    )

    weights = dict(
        zip(
            df["Feature"],
            df["Adaptive_Weight"],
        )
    )

    feature_rank = dict(
        zip(
            df["Feature"],
            df["Feature_Rank"].astype(int),
        )
    )

    metadata = {
        "n_features": len(df),
        "weight_sum": weight_sum,
        "normalized": normalized,
        "source_file": str(csv_path),
    }

    return FeatureWeightConfig(
        features=features,
        weights=weights,
        feature_rank=feature_rank,
        metadata=metadata,
    )


# ============================================================
# PRETTY PRINT
# ============================================================

def print_feature_config(
    config: FeatureWeightConfig
) -> None:
    """
    Pretty-print configuration.
    """

    print("\n====================================")
    print("PRODUCTION FEATURE CONFIG")
    print("====================================")

    print(f"Features      : {config.metadata['n_features']}")
    print(f"Weight Sum    : {config.metadata['weight_sum']:.6f}")
    print(f"Normalized    : {config.metadata['normalized']}")

    print()

    for feature in config.features:
        print(
            f"{config.feature_rank[feature]:>2}. "
            f"{feature:<25}"
            f"{config.weights[feature]:.4f}"
        )

    print("====================================")




# ======================================================
# EXAMPLE USAGE
# ======================================================
# from scoring.feature_config import (
#     load_feature_config,
#     print_feature_config,
# )

# config = load_feature_config(
#     "data/master_table_ic.csv"
# )

# print_feature_config(config)
# ======================================================