"""
============================================================
PORTFOLIO WEIGHTING ENGINE
Part 1 — Framework
============================================================

Institutional-grade weighting framework.

Contains
--------
* Constants
* Dataclasses
* Validation
* Base Engine
* Shared Utilities
* Diagnostics Containers

No weighting algorithms implemented here.

============================================================
"""

from __future__ import annotations

from abc import ABC, abstractmethod
from dataclasses import dataclass, field
from typing import Dict, Optional, Any

import numpy as np
import pandas as pd

from .config import (
    PortfolioSelectionConfig,
    WeightMethod,
    SelectionMethod,
)

from .config import (
    PortfolioSelectionConfig,
    WeightMethod,
)

# ============================================================
# CONSTANTS
# ============================================================

EPS = 1e-12

LONG = "Long"

SHORT = "Short"

NEUTRAL = "Neutral"

DEFAULT_WEIGHT_COLUMN = "Portfolio_Weight"

DEFAULT_SIDE_COLUMN = "Portfolio_Side"


# ============================================================
# RESULT OBJECTS
# ============================================================

@dataclass(slots=True)
class WeightDiagnostics:
    """
    Diagnostics generated by weighting engine.
    """

    gross_exposure: float = 0.0

    net_exposure: float = 0.0

    max_weight: float = 0.0

    min_weight: float = 0.0

    effective_n: float = 0.0

    concentration_hhi: float = 0.0

    metadata: Dict[str, Any] = field(
        default_factory=dict
    )


@dataclass(slots=True)
class WeightResult:
    """
    Weighting output.
    """

    weighted_df: pd.DataFrame

    diagnostics: WeightDiagnostics


# ============================================================
# VALIDATION
# ============================================================

def validate_selected_portfolio(
    df: pd.DataFrame,
    config: PortfolioSelectionConfig,
) -> None:
    """
    Validate portfolio input.
    """

    required = [

        "Date",

        config.selected_column,

        config.score_column,
    ]

    missing = [
        col
        for col in required
        if col not in df.columns
    ]

    if missing:

        raise ValueError(
            f"Missing required columns: {missing}"
        )

    if df.empty:

        raise ValueError(
            "Portfolio dataframe is empty."
        )

    selected_count = int(
        df[config.selected_column].sum()
    )

    if selected_count == 0:

        raise ValueError(
            "No securities selected."
        )


# ============================================================
# SHARED UTILITIES
# ============================================================

def normalize_weights(
    weights: pd.Series,
) -> pd.Series:
    """
    Normalize weights to sum to 1.
    """

    total = float(weights.sum())

    if abs(total) < EPS:

        return pd.Series(
            0.0,
            index=weights.index,
        )

    return weights / total


def normalize_long_short(
    weights: pd.Series,
    gross_target: float = 1.0,
) -> pd.Series:
    """
    Normalize by gross exposure.
    """

    gross = float(
        np.abs(weights).sum()
    )

    if gross < EPS:

        return pd.Series(
            0.0,
            index=weights.index,
        )

    return (
        weights
        / gross
        * gross_target
    )


def effective_number_of_positions(
    weights: pd.Series,
) -> float:
    """
    Effective N.

    1 / sum(w^2)
    """

    w = weights.fillna(0.0)

    denom = float(
        (w ** 2).sum()
    )

    if denom < EPS:

        return 0.0

    return 1.0 / denom


def concentration_hhi(
    weights: pd.Series,
) -> float:
    """
    Herfindahl-Hirschman Index.
    """

    w = weights.fillna(0.0)

    return float(
        (w ** 2).sum()
    )


def apply_weight_caps(
    weights: pd.Series,
    min_weight: float,
    max_weight: float,
) -> pd.Series:
    """
    Apply weight bounds.

    Re-normalization handled elsewhere.
    """

    return weights.clip(
        lower=min_weight,
        upper=max_weight,
    )


# ============================================================
# BASE ENGINE
# ============================================================

class BaseWeightEngine(ABC):
    """
    Abstract weighting engine.
    """

    def __init__(
        self,
        config: PortfolioSelectionConfig,
    ) -> None:

        self.config = config

    @abstractmethod
    def compute_weights(
        self,
        group: pd.DataFrame,
    ) -> pd.Series:
        """
        Compute raw weights.
        """

        raise NotImplementedError

    def apply_constraints(
        self,
        weights: pd.Series,
    ) -> pd.Series:
        """
        Apply portfolio constraints.
        """

        weights = apply_weight_caps(
            weights,
            self.config.min_weight,
            self.config.max_weight,
        )

        return normalize_weights(
            weights
        )

    def build_diagnostics(
        self,
        weights: pd.Series,
    ) -> WeightDiagnostics:
        """
        Build diagnostics object.
        """

        return WeightDiagnostics(

            gross_exposure=float(
                np.abs(weights).sum()
            ),

            net_exposure=float(
                weights.sum()
            ),

            max_weight=float(
                weights.max()
            ),

            min_weight=float(
                weights.min()
            ),

            effective_n=
                effective_number_of_positions(
                    weights
                ),

            concentration_hhi=
                concentration_hhi(
                    weights
                ),
        )


# PART 2 — WEIGHT ENGINES
# EqualWeightEngine
# ScoreWeightEngine
# SoftmaxWeightEngine
# InverseVolatilityEngine
# KellyWeightEngine
# RiskParityEngine
# WeightEngineFactory

# ============================================================
# EQUAL WEIGHT ENGINE
# ============================================================

class EqualWeightEngine(
    BaseWeightEngine
):

    def compute_weights(
        self,
        group: pd.DataFrame,
    ) -> pd.Series:

        n = len(group)

        if n == 0:

            return pd.Series(
                dtype=float,
                index=group.index,
            )

        return pd.Series(
            1.0 / n,
            index=group.index,
        )


# ============================================================
# SCORE WEIGHT ENGINE
# ============================================================

class ScoreWeightEngine(
    BaseWeightEngine
):

    def compute_weights(
        self,
        group: pd.DataFrame,
    ) -> pd.Series:

        scores = (
            group[
                self.config.score_column
            ]
            .fillna(0.0)
            .clip(lower=0.0)
        )

        return normalize_weights(
            scores
        )


# ============================================================
# SOFTMAX ENGINE
# ============================================================

class SoftmaxWeightEngine(
    BaseWeightEngine
):

    def __init__(
        self,
        config: PortfolioSelectionConfig,
    ) -> None:

        super().__init__(config)

        self.temperature = getattr(
            config,
            "softmax_temperature",
            1.0,
        )

    def compute_weights(
        self,
        group: pd.DataFrame,
    ) -> pd.Series:

        scores = (
            group[
                self.config.score_column
            ]
            .fillna(0.0)
        )

        scores = (
            scores
            - scores.max()
        )

        exp_scores = np.exp(
            scores
            / max(
                self.temperature,
                EPS,
            )
        )

        return normalize_weights(
            pd.Series(
                exp_scores,
                index=group.index,
            )
        )


# ============================================================
# INVERSE VOLATILITY ENGINE
# ============================================================

class InverseVolatilityEngine(
    BaseWeightEngine
):

    def __init__(
        self,
        config: PortfolioSelectionConfig,
        volatility_column: str = (
            "Volatility"
        ),
    ) -> None:

        super().__init__(config)

        self.volatility_column = (
            volatility_column
        )

    def compute_weights(
        self,
        group: pd.DataFrame,
    ) -> pd.Series:

        if (
            self.volatility_column
            not in group.columns
        ):

            return EqualWeightEngine(
                self.config
            ).compute_weights(
                group
            )

        vol = (
            group[
                self.volatility_column
            ]
            .replace(
                0,
                np.nan,
            )
            .fillna(
                group[
                    self.volatility_column
                ].median()
            )
            .clip(
                lower=EPS
            )
        )

        inv_vol = 1.0 / vol

        return normalize_weights(
            inv_vol
        )


# ============================================================
# KELLY ENGINE
# ============================================================

class KellyWeightEngine(
    BaseWeightEngine
):
    """
    Simplified Kelly sizing.

    Full Kelly implementation
    added after expected-return
    engine and risk model
    are available.
    """

    def compute_weights(
        self,
        group: pd.DataFrame,
    ) -> pd.Series:

        scores = (
            group[
                self.config.score_column
            ]
            .fillna(0.0)
        )

        scores = scores.clip(
            lower=0.0
        )

        return normalize_weights(
            scores
        )


# ============================================================
# RISK PARITY ENGINE
# ============================================================

class RiskParityEngine(
    BaseWeightEngine
):
    """
    Placeholder.

    Full covariance-based
    implementation handled
    in optimizer.py.
    """

    def compute_weights(
        self,
        group: pd.DataFrame,
    ) -> pd.Series:

        return EqualWeightEngine(
            self.config
        ).compute_weights(
            group
        )


# ============================================================
# OPTIMIZER-BASED ENGINES
# ============================================================

class MaxSharpeEngine(
    BaseWeightEngine
):

    def compute_weights(
        self,
        group: pd.DataFrame,
    ) -> pd.Series:

        raise NotImplementedError(
            "Implemented in optimizer.py"
        )


class MinVarianceEngine(
    BaseWeightEngine
):

    def compute_weights(
        self,
        group: pd.DataFrame,
    ) -> pd.Series:

        raise NotImplementedError(
            "Implemented in optimizer.py"
        )


class HRPEngine(
    BaseWeightEngine
):

    def compute_weights(
        self,
        group: pd.DataFrame,
    ) -> pd.Series:

        raise NotImplementedError(
            "Implemented in optimizer.py"
        )


class ERCEngine(
    BaseWeightEngine
):

    def compute_weights(
        self,
        group: pd.DataFrame,
    ) -> pd.Series:

        raise NotImplementedError(
            "Implemented in optimizer.py"
        )


# ============================================================
# FACTORY
# ============================================================

class WeightEngineFactory:

    @staticmethod
    def create(
        method: WeightMethod,
        config: PortfolioSelectionConfig,
    ) -> BaseWeightEngine:

        if method == WeightMethod.EQUAL:
            return EqualWeightEngine(
                config
            )

        if method == WeightMethod.SCORE:
            return ScoreWeightEngine(
                config
            )

        if method == WeightMethod.SOFTMAX:
            return SoftmaxWeightEngine(
                config
            )

        if (
            method
            == WeightMethod.INVERSE_VOLATILITY
        ):
            return (
                InverseVolatilityEngine(
                    config
                )
            )

        if method == WeightMethod.KELLY:
            return KellyWeightEngine(
                config
            )

        if (
            method
            == WeightMethod.RISK_PARITY
        ):
            return RiskParityEngine(
                config
            )

        if (
            hasattr(
                WeightMethod,
                "MAX_SHARPE"
            )
            and method
            == WeightMethod.MAX_SHARPE
        ):
            return MaxSharpeEngine(
                config
            )

        if (
            hasattr(
                WeightMethod,
                "MIN_VARIANCE"
            )
            and method
            == WeightMethod.MIN_VARIANCE
        ):
            return MinVarianceEngine(
                config
            )

        if (
            hasattr(
                WeightMethod,
                "HRP"
            )
            and method
            == WeightMethod.HRP
        ):
            return HRPEngine(
                config
            )

        if (
            hasattr(
                WeightMethod,
                "ERC"
            )
            and method
            == WeightMethod.ERC
        ):
            return ERCEngine(
                config
            )

        raise ValueError(
            f"Unknown weighting method: {method}"
        )


# PART 3: PORTFOLIO WEIGHT CONSTRUCTION
# compute_weights_by_date()
# long-only portfolio weights
# long-short portfolio weights
# gross exposure normalization
# net exposure normalization
# cash buffer handling
# application of constraints

# ============================================================
# LONG ONLY CONSTRUCTION
# ============================================================

def construct_long_only_weights(
    group: pd.DataFrame,
    engine: BaseWeightEngine,
) -> pd.Series:
    """
    Build long-only portfolio.
    """

    raw_weights = (
        engine.compute_weights(
            group
        )
    )

    weights = (
        engine.apply_constraints(
            raw_weights
        )
    )

    return weights


# ============================================================
# LONG SHORT CONSTRUCTION
# ============================================================

def construct_long_short_weights(
    group: pd.DataFrame,
    engine: BaseWeightEngine,
    config: PortfolioSelectionConfig,
) -> pd.Series:
    """
    Construct long-short portfolio.
    """

    longs = group.loc[
        group[
            DEFAULT_SIDE_COLUMN
        ]
        == LONG
    ]

    shorts = group.loc[
        group[
            DEFAULT_SIDE_COLUMN
        ]
        == SHORT
    ]

    long_weights = pd.Series(
        0.0,
        index=group.index,
    )

    short_weights = pd.Series(
        0.0,
        index=group.index,
    )

    # ---------------------------------
    # Long book
    # ---------------------------------

    if not longs.empty:

        lw = engine.compute_weights(
            longs
        )

        lw = normalize_weights(
            lw
        )

        long_weights.loc[
            longs.index
        ] = lw

    # ---------------------------------
    # Short book
    # ---------------------------------

    if not shorts.empty:

        sw = engine.compute_weights(
            shorts
        )

        sw = normalize_weights(
            sw
        )

        short_weights.loc[
            shorts.index
        ] = -sw

    weights = (
        long_weights
        + short_weights
    )

    return weights


# ============================================================
# DATE LEVEL CONSTRUCTION
# ============================================================

def construct_weights_for_date(
    group: pd.DataFrame,
    config: PortfolioSelectionConfig,
) -> pd.Series:
    """
    Construct weights
    for a single rebalance date.
    """

    engine = (
        WeightEngineFactory.create(
            config.weight_method,
            config,
        )
    )

    if (
        config.selection_method
        == SelectionMethod.LONG_ONLY
    ):

        weights = (
            construct_long_only_weights(
                group,
                engine,
            )
        )

    else:

        weights = (
            construct_long_short_weights(
                group,
                engine,
                config,
            )
        )

    weights = apply_exposure_targets(
        weights,
        config,
    )

    return weights


# ============================================================
# PORTFOLIO CONSTRUCTION
# ============================================================

def compute_portfolio_weights(
    portfolio_df: pd.DataFrame,
    config: PortfolioSelectionConfig,
) -> WeightResult:
    """
    Main weighting API.
    """

    validate_selected_portfolio(
        portfolio_df,
        config,
    )

    out = (
        portfolio_df.copy()
    )

    out[
        config.weight_column
    ] = 0.0

    selected = out.loc[
        out[
            config.selected_column
        ]
    ].copy()

    if selected.empty:

        diagnostics = (
            WeightDiagnostics()
        )

        return WeightResult(
            weighted_df=out,
            diagnostics=diagnostics,
        )

    # ---------------------------------
    # Rebalance Date Loop
    # ---------------------------------

    for (
        date,
        group,
    ) in selected.groupby(
        "Date"
    ):

        weights = (
            construct_weights_for_date(
                group,
                config,
            )
        )

        out.loc[
            group.index,
            config.weight_column,
        ] = (
            weights.values
        )

    # ---------------------------------
    # Portfolio Diagnostics
    # ---------------------------------

    final_weights = (
        out[
            config.weight_column
        ]
    )

    diagnostics = (
        WeightDiagnostics(
            gross_exposure=float(
                np.abs(
                    final_weights
                ).sum()
            ),
            net_exposure=float(
                final_weights.sum()
            ),
            max_weight=float(
                final_weights.max()
            ),
            min_weight=float(
                final_weights.min()
            ),
            effective_n=
            effective_number_of_positions(
                final_weights
            ),
            concentration_hhi=
            concentration_hhi(
                final_weights
            ),
        )
    )

    return WeightResult(
        weighted_df=out,
        diagnostics=diagnostics,
    )

# PART 4: EXPOSURE TARGETING
# Long exposure reporting
# Short exposure reporting
# Gross leverage reporting
# Institutional long-short scaling

# ============================================================
# GROSS EXPOSURE TARGETING
# ============================================================

def target_gross_exposure(
    weights: pd.Series,
    target_gross: float,
) -> pd.Series:
    """
    Scale portfolio
    to desired gross exposure.
    """

    gross = float(
        np.abs(weights).sum()
    )

    if gross < EPS:

        return weights.copy()

    scale = (
        target_gross
        / gross
    )

    return weights * scale


# ============================================================
# NET EXPOSURE TARGETING
# ============================================================

def target_net_exposure(
    weights: pd.Series,
    target_net: float,
) -> pd.Series:
    """
    Adjust portfolio
    toward desired net exposure.
    """

    current_net = float(
        weights.sum()
    )

    adjustment = (
        target_net
        - current_net
    )

    n = len(weights)

    if n == 0:

        return weights

    return (
        weights
        + adjustment / n
    )


# ============================================================
# LONG SHORT NORMALIZATION
# ============================================================

def normalize_long_short_books(
    weights: pd.Series,
    target_gross: float,
    target_net: float,
) -> pd.Series:
    """
    Institutional long-short scaling.
    """

    weights = (
        target_gross_exposure(
            weights,
            target_gross,
        )
    )

    weights = (
        target_net_exposure(
            weights,
            target_net,
        )
    )

    return weights


# ============================================================
# LONG BOOK EXPOSURE
# ============================================================

def long_exposure(
    weights: pd.Series,
) -> float:

    return float(
        weights[
            weights > 0
        ].sum()
    )


# ============================================================
# SHORT BOOK EXPOSURE
# ============================================================

def short_exposure(
    weights: pd.Series,
) -> float:

    return float(
        np.abs(
            weights[
                weights < 0
            ]
        ).sum()
    )


# ============================================================
# GROSS EXPOSURE
# ============================================================

def gross_exposure(
    weights: pd.Series,
) -> float:

    return float(
        np.abs(weights).sum()
    )


# ============================================================
# NET EXPOSURE
# ============================================================

def net_exposure(
    weights: pd.Series,
) -> float:

    return float(
        weights.sum()
    )


# ============================================================
# EXPOSURE DIAGNOSTICS
# ============================================================

def exposure_summary(
    weights: pd.Series,
) -> dict:
    """
    Exposure diagnostics.
    """

    return {

        "long_exposure":
            long_exposure(
                weights
            ),

        "short_exposure":
            short_exposure(
                weights
            ),

        "gross_exposure":
            gross_exposure(
                weights
            ),

        "net_exposure":
            net_exposure(
                weights
            ),
    }


# ============================================================
# APPLY TARGETS
# ============================================================

def apply_exposure_targets(
    weights: pd.Series,
    config: PortfolioSelectionConfig,
) -> pd.Series:
    """
    Master exposure targeting.
    """

    if (
        config.selection_method
        == SelectionMethod.LONG_ONLY
    ):

        return target_gross_exposure(
            weights,
            config.gross_exposure_target,
        )

    return normalize_long_short_books(
        weights,
        config.gross_exposure_target,
        config.net_exposure_target,
    )

# PART 5: CASH HANDLING
# cash buffer
# residual cash
# investable capital normalization
# institutional portfolio funding model.

# ============================================================
# CASH COLUMN
# ============================================================

DEFAULT_CASH_COLUMN = (
    "Cash_Weight"
)


# ============================================================
# COMPUTE CASH BUFFER
# ============================================================

def compute_cash_weight(
    config: PortfolioSelectionConfig,
) -> float:
    """
    Portfolio cash allocation.
    """

    return float(
        config.cash_buffer
    )


# ============================================================
# INVESTABLE CAPITAL
# ============================================================

def investable_capital_fraction(
    config: PortfolioSelectionConfig,
) -> float:
    """
    Capital available for positions.
    """

    return (
        1.0
        - config.cash_buffer
    )


# ============================================================
# SCALE PORTFOLIO TO CASH BUFFER
# ============================================================

def apply_cash_buffer(
    weights: pd.Series,
    config: PortfolioSelectionConfig,
) -> pd.Series:
    """
    Reserve cash from portfolio.
    """

    investable = (
        investable_capital_fraction(
            config
        )
    )

    return (
        weights
        * investable
    )


# ============================================================
# ADD CASH ROW
# ============================================================

def append_cash_position(
    portfolio_df: pd.DataFrame,
    config: PortfolioSelectionConfig,
) -> pd.DataFrame:
    """
    Optional synthetic cash position.
    """

    cash_weight = (
        compute_cash_weight(
            config
        )
    )

    if cash_weight <= 0:

        return portfolio_df

    rows = []

    for date in (
        portfolio_df["Date"]
        .drop_duplicates()
    ):

        rows.append({

            "Date": date,

            "Ticker": "CASH",

            config.weight_column:
                cash_weight,

            DEFAULT_CASH_COLUMN:
                cash_weight,

            DEFAULT_SIDE_COLUMN:
                NEUTRAL,
        })

    cash_df = pd.DataFrame(
        rows
    )

    return pd.concat(
        [
            portfolio_df,
            cash_df,
        ],
        ignore_index=True,
    )


# ============================================================
# REMOVE TINY POSITIONS
# ============================================================

def remove_small_positions(
    weights: pd.Series,
    threshold: float,
) -> pd.Series:
    """
    Eliminate tiny positions.
    """

    cleaned = weights.copy()

    cleaned[
        np.abs(cleaned)
        < threshold
    ] = 0.0

    return cleaned


# ============================================================
# REDISTRIBUTE REMAINING CAPITAL
# ============================================================

def redistribute_after_pruning(
    weights: pd.Series,
) -> pd.Series:
    """
    Re-normalize after removing
    tiny positions.
    """

    gross = float(
        np.abs(weights).sum()
    )

    if gross < EPS:

        return weights

    return (
        weights
        / gross
    )


# ============================================================
# FULL CASH PROCESSING
# ============================================================

def apply_cash_management(
    weights: pd.Series,
    config: PortfolioSelectionConfig,
) -> pd.Series:
    """
    Institutional cash workflow.
    """

    weights = (
        remove_small_positions(
            weights,
            config.min_trade_weight,
        )
    )

    weights = (
        redistribute_after_pruning(
            weights
        )
    )

    weights = (
        apply_cash_buffer(
            weights,
            config,
        )
    )

    return weights


# ============================================================
# CASH DIAGNOSTICS
# ============================================================

def cash_summary(
    config: PortfolioSelectionConfig,
) -> dict:
    """
    Cash allocation summary.
    """

    return {

        "cash_weight":
            config.cash_buffer,

        "investable_capital":
            (
                1.0
                - config.cash_buffer
            ),
    }

# PART 6: DIAGNOSTICS
# ===================
# concentration metrics
# effective number of positions
# long/short counts
# top holdings
# diversification scores
# weight distribution analytics.


# ============================================================
# POSITION COUNTS
# ============================================================

def position_count(
    weights: pd.Series,
) -> int:
    """
    Number of active positions.
    """

    return int(
        (np.abs(weights) > EPS).sum()
    )


def long_position_count(
    weights: pd.Series,
) -> int:
    """
    Number of long positions.
    """

    return int(
        (weights > EPS).sum()
    )


def short_position_count(
    weights: pd.Series,
) -> int:
    """
    Number of short positions.
    """

    return int(
        (weights < -EPS).sum()
    )


# ============================================================
# TOP HOLDINGS
# ============================================================

def top_holdings(
    portfolio_df: pd.DataFrame,
    config: PortfolioSelectionConfig,
    n: int = 10,
) -> pd.DataFrame:
    """
    Largest portfolio positions.
    """

    return (
        portfolio_df
        .sort_values(
            config.weight_column,
            ascending=False,
        )
        .head(n)
        .copy()
    )


# ============================================================
# CONCENTRATION
# ============================================================

def concentration_ratio(
    weights: pd.Series,
    top_n: int = 5,
) -> float:
    """
    Top-N concentration.
    """

    w = (
        np.abs(weights)
        .sort_values(
            ascending=False
        )
        .head(top_n)
    )

    return float(
        w.sum()
    )


# ============================================================
# EFFECTIVE NUMBER OF POSITIONS
# ============================================================

def diversification_score(
    weights: pd.Series,
) -> float:
    """
    Diversification score.

    Effective N normalized
    by actual position count.
    """

    active = position_count(
        weights
    )

    if active == 0:

        return 0.0

    eff_n = (
        effective_number_of_positions(
            weights
        )
    )

    return float(
        eff_n / active
    )


# ============================================================
# WEIGHT DISTRIBUTION
# ============================================================

def weight_distribution(
    weights: pd.Series,
) -> dict:
    """
    Distribution statistics.
    """

    w = weights.fillna(0.0)

    return {

        "mean":
            float(w.mean()),

        "std":
            float(w.std()),

        "min":
            float(w.min()),

        "max":
            float(w.max()),

        "median":
            float(w.median()),

        "p25":
            float(
                w.quantile(0.25)
            ),

        "p75":
            float(
                w.quantile(0.75)
            ),
    }


# ============================================================
# DATE LEVEL DIAGNOSTICS
# ============================================================

def diagnostics_by_date(
    portfolio_df: pd.DataFrame,
    config: PortfolioSelectionConfig,
) -> pd.DataFrame:
    """
    Portfolio diagnostics
    for every rebalance date.
    """

    rows = []

    for (
        date,
        group,
    ) in portfolio_df.groupby(
        "Date"
    ):

        weights = (
            group[
                config.weight_column
            ]
            .fillna(0.0)
        )

        rows.append({

            "Date": date,

            "Positions":
                position_count(
                    weights
                ),

            "Longs":
                long_position_count(
                    weights
                ),

            "Shorts":
                short_position_count(
                    weights
                ),

            "GrossExposure":
                gross_exposure(
                    weights
                ),

            "NetExposure":
                net_exposure(
                    weights
                ),

            "EffectiveN":
                effective_number_of_positions(
                    weights
                ),

            "HHI":
                concentration_hhi(
                    weights
                ),

            "Top5Concentration":
                concentration_ratio(
                    weights,
                    5,
                ),

            "Diversification":
                diversification_score(
                    weights
                ),
        })

    return pd.DataFrame(
        rows
    )


# ============================================================
# FULL PORTFOLIO DIAGNOSTICS
# ============================================================

def portfolio_diagnostics(
    portfolio_df: pd.DataFrame,
    config: PortfolioSelectionConfig,
) -> dict:
    """
    Portfolio-wide diagnostics.
    """

    weights = (
        portfolio_df[
            config.weight_column
        ]
        .fillna(0.0)
    )

    diagnostics = {

        # exposures
        **exposure_summary(
            weights
        ),

        # counts
        "positions":
            position_count(
                weights
            ),

        "long_positions":
            long_position_count(
                weights
            ),

        "short_positions":
            short_position_count(
                weights
            ),

        # diversification
        "effective_n":
            effective_number_of_positions(
                weights
            ),

        "diversification_score":
            diversification_score(
                weights
            ),

        "concentration_hhi":
            concentration_hhi(
                weights
            ),

        "top5_concentration":
            concentration_ratio(
                weights,
                5,
            ),

        "top10_concentration":
            concentration_ratio(
                weights,
                10,
            ),
    }

    diagnostics.update(
        weight_distribution(
            weights
        )
    )

    return diagnostics

# PART 7: REPORTING
# =================
# weight summary reports
# top holdings reports
# exposure reports
# diagnostics exports
# dashboard-ready outputs.


# ============================================================
# PORTFOLIO SUMMARY REPORT
# ============================================================

def portfolio_summary_report(
    portfolio_df: pd.DataFrame,
    config: PortfolioSelectionConfig,
) -> pd.DataFrame:
    """
    High-level portfolio report.
    """

    diagnostics = portfolio_diagnostics(
        portfolio_df,
        config,
    )

    return pd.DataFrame(
        [
            {
                "Metric": k,
                "Value": v,
            }
            for k, v
            in diagnostics.items()
        ]
    )


# ============================================================
# TOP HOLDINGS REPORT
# ============================================================

def top_holdings_report(
    portfolio_df: pd.DataFrame,
    config: PortfolioSelectionConfig,
    top_n: int = 20,
) -> pd.DataFrame:
    """
    Largest holdings report.
    """

    cols = [
        c
        for c in [

            "Date",

            "Ticker",

            config.score_column,

            config.weight_column,

            DEFAULT_SIDE_COLUMN,
        ]
        if c in portfolio_df.columns
    ]

    return (
        portfolio_df
        .sort_values(
            config.weight_column,
            ascending=False,
        )[cols]
        .head(top_n)
        .copy()
    )


# ============================================================
# EXPOSURE REPORT
# ============================================================

def exposure_report(
    portfolio_df: pd.DataFrame,
    config: PortfolioSelectionConfig,
) -> pd.DataFrame:
    """
    Exposure by date.
    """

    rows = []

    for (
        date,
        group,
    ) in portfolio_df.groupby(
        "Date"
    ):

        weights = (
            group[
                config.weight_column
            ]
            .fillna(0.0)
        )

        rows.append({

            "Date": date,

            "LongExposure":
                long_exposure(
                    weights
                ),

            "ShortExposure":
                short_exposure(
                    weights
                ),

            "GrossExposure":
                gross_exposure(
                    weights
                ),

            "NetExposure":
                net_exposure(
                    weights
                ),
        })

    return pd.DataFrame(
        rows
    )


# ============================================================
# CONCENTRATION REPORT
# ============================================================

def concentration_report(
    portfolio_df: pd.DataFrame,
    config: PortfolioSelectionConfig,
) -> pd.DataFrame:
    """
    Concentration statistics by date.
    """

    rows = []

    for (
        date,
        group,
    ) in portfolio_df.groupby(
        "Date"
    ):

        weights = (
            group[
                config.weight_column
            ]
            .fillna(0.0)
        )

        rows.append({

            "Date": date,

            "HHI":
                concentration_hhi(
                    weights
                ),

            "Top5":
                concentration_ratio(
                    weights,
                    5,
                ),

            "Top10":
                concentration_ratio(
                    weights,
                    10,
                ),

            "EffectiveN":
                effective_number_of_positions(
                    weights
                ),
        })

    return pd.DataFrame(
        rows
    )


# ============================================================
# WEIGHT DISTRIBUTION REPORT
# ============================================================

def weight_distribution_report(
    portfolio_df: pd.DataFrame,
    config: PortfolioSelectionConfig,
) -> pd.DataFrame:
    """
    Weight distribution report.
    """

    stats = weight_distribution(

        portfolio_df[
            config.weight_column
        ]
    )

    return pd.DataFrame(
        [
            {
                "Statistic": k,
                "Value": v,
            }
            for k, v
            in stats.items()
        ]
    )


# ============================================================
# DIAGNOSTICS PACKAGE
# ============================================================

def diagnostics_package(
    portfolio_df: pd.DataFrame,
    config: PortfolioSelectionConfig,
) -> dict:
    """
    Full diagnostics package.

    Dashboard-ready.
    """

    return {

        "summary":
            portfolio_summary_report(
                portfolio_df,
                config,
            ),

        "top_holdings":
            top_holdings_report(
                portfolio_df,
                config,
            ),

        "exposures":
            exposure_report(
                portfolio_df,
                config,
            ),

        "concentration":
            concentration_report(
                portfolio_df,
                config,
            ),

        "distribution":
            weight_distribution_report(
                portfolio_df,
                config,
            ),

        "by_date":
            diagnostics_by_date(
                portfolio_df,
                config,
            ),
    }


# ============================================================
# EXPORT TO EXCEL
# ============================================================

def export_weighting_report(
    portfolio_df: pd.DataFrame,
    config: PortfolioSelectionConfig,
    filepath: str,
) -> None:
    """
    Export diagnostics workbook.
    """

    package = diagnostics_package(
        portfolio_df,
        config,
    )

    with pd.ExcelWriter(
        filepath
    ) as writer:

        for (
            name,
            report,
        ) in package.items():

            report.to_excel(
                writer,
                sheet_name=name[:31],
                index=False,
            )


# ============================================================
# DASHBOARD DATA
# ============================================================

def dashboard_data(
    portfolio_df: pd.DataFrame,
    config: PortfolioSelectionConfig,
) -> dict:
    """
    Lightweight dashboard payload.
    """

    return {

        "summary":
            portfolio_diagnostics(
                portfolio_df,
                config,
            ),

        "top_holdings":
            top_holdings_report(
                portfolio_df,
                config,
                top_n=10,
            ),

        "exposures":
            exposure_report(
                portfolio_df,
                config,
            ),

        "concentration":
            concentration_report(
                portfolio_df,
                config,
            ),
    }
 
# ============================================================
# EXPORTS
# ============================================================


__all__ = [

    "WeightDiagnostics",
    "WeightResult",

    "WeightEngineFactory",

    "compute_portfolio_weights",

    "portfolio_diagnostics",
    "diagnostics_by_date",

    "portfolio_summary_report",
    "top_holdings_report",
    "exposure_report",
    "concentration_report",

    "export_weighting_report",
    "dashboard_data",
]
